version: "3.1"
services:
  web:
    build: .
    ports: 
      - "80:80"
    volumes:
      - ./www:/var/www/html
    links:
      - base_datos
    networks:
      - default
  base_datos:
    image: mysql:8.0
    ports: 
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: tienda
      MYSQL_ROOT_PASSWORD: test 
    volumes:
      - ./data_base:/docker-entrypoint-initdb.d
      - ./conf:/etc/mysql/conf.d
      - persistent:/var/lib/mysql
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
        PMA_HOST: base_datos
        MYSQL_USER: root
        MYSQL_PASSWORD: test
        MYSQL_ROOT_PASSWORD: test
    ports:
      - 8000:80
volumes:
  persistent:
 
